### ISSUE TITLE
FakeHost

### ISSUE THREAD

**Issue by abovenetwork** [briancline/ircplanet#8]
Problm with fakehost....

When setting a ban and user join channel, service receive real user IP not the fakehost, so ban don't work

problm on NickServ, See Real Host and No the fakehost...

**Comment by briancline** [comment]
Thanks for reporting this. 

I'd like to reproduce this in a test environment. Which variant and version of ircu are you using?

**Comment by briancline** [comment]
This looks to be working correctly now with the above commit applied.
